export const AllCoursesData = [
	{
			id: 1,
			category: 'الرياضيات',
			image: '/assets/images/course/course-python.jpg',
			title: 'الزوايا المركزية والزوايا المحيطية في دائرة',
			date_added: 'أضيف في 7 يوليو، 2020',
			instructor_name: 'محمد العلوي',
			instructor_image: '/assets/images/avatar/avatar-1.jpg',
			status: 'معلق',
			level: 'متوسط',
			duration: '1س 46د',
			price: 850,
			discount: 50,
			rating: 2.0,
			ratingby: 16500,
			recommended: false,
			popular: false,
			trending: true,
			progress: 45
	},
	{
			id: 2,
			category: 'الفيزياء',
			image: '/assets/images/course/course-angular.jpg',
			title: 'مقدمة إلى فيزياء الجسيمات للمبتدئين',
			date_added: 'أضيف في 6 يوليو، 2021',
			instructor_name: 'سارة بنسعيد',
			instructor_image: '/assets/images/avatar/avatar-2.jpg',
			status: 'معلق',
			level: 'متقدم',
			duration: '2س 40د',
			price: 600,
			discount: 100,
			rating: 2.5,
			ratingby: 1500,
			recommended: true,
			popular: false,
			trending: false,
			progress: 95
	},
	{
			id: 3,
			category: 'الفلسفة',
			image: '/assets/images/course/course-node.jpg',
			title: 'دورة كاملة في الفلسفة - دليل للمبتدئين',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'علي الصغير',
			instructor_image: '/assets/images/avatar/avatar-3.jpg',
			status: 'معلق',
			level: 'مبتدئ',
			duration: '3س 16د',
			price: 700,
			discount: 150,
			rating: 3.0,
			ratingby: 1600,
			recommended: false,
			popular: true,
			trending: true,
			progress: 55
	},
	{
			id: 4,
			category: 'الرياضيات',
			image: '/assets/images/course/course-python.jpg',
			title: 'دليل كامل للمبتدئين في الرياضيات',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'فاطمة الزهراء',
			instructor_image: '/assets/images/avatar/avatar-4.jpg',
			status: 'مباشر',
			level: 'متقدم',
			duration: '4س 10د',
			price: 850,
			discount: 150,
			rating: 3.5,
			ratingby: 7500,
			recommended: true,
			popular: true,
			trending: false,
			progress: 50
	},
	{
			id: 5,
			category: 'الفيزياء',
			image: '/assets/images/course/course-angular.jpg',
			title: 'بدء تطوير الفيزياء باستخدام تجربة وبيانات',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'سعيد الجابري',
			instructor_image: '/assets/images/avatar/avatar-5.jpg',
			status: 'مباشر',
			level: 'متوسط',
			duration: '2س 00د',
			price: 950,
			discount: 150,
			rating: 4.0,
			ratingby: 15700,
			recommended: true,
			popular: true,
			trending: true,
			progress: 45
	},
	{
			id: 6,
			category: 'الفلسفة',
			image: '/assets/images/course/course-node.jpg',
			title: 'الفلسفة: دليل المبتدئين الشامل لتعلم الفلسفة خطوة بخطوة',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'جميلة العراوي',
			instructor_image: '/assets/images/avatar/avatar-6.jpg',
			status: 'مباشر',
			level: 'مبتدئ',
			duration: '1س 00د',
			price: 220,
			discount: 50,
			rating: 4.5,
			ratingby: 2500,
			recommended: true,
			popular: false,
			trending: true,
			progress: 65
	},
	{
			id: 7,
			category: 'الرياضيات',
			image: '/assets/images/course/course-python.jpg',
			title: 'كيفية إنشاء موقع ويب بسهولة باستخدام الرياضيات',
			date_added: 'أضيف في 4 يوليو، 2021',
			instructor_name: 'عمر المراكشي',
			instructor_image: '/assets/images/avatar/avatar-7.jpg',
			status: 'مباشر',
			level: 'متقدم',
			duration: '3س 55د',
			price: 750,
			discount: 150,
			rating: 4.5,
			ratingby: 1500,
			recommended: true,
			popular: true,
			trending: true,
			progress: 75
	},
	{
			id: 8,
			category: 'الفلسفة',
			image: '/assets/images/course/course-node.jpg',
			title: 'الفلسفة - الدليل الكامل للمبتدئين',
			date_added: 'أضيف في 3 يوليو، 2021',
			instructor_name: 'يوسف بنحسن',
			instructor_image: '/assets/images/avatar/avatar-8.jpg',
			status: 'معلق',
			level: 'متوسط',
			duration: '2س 46د',
			price: 750,
			discount: 150,
			rating: 4.5,
			ratingby: 1600,
			recommended: true,
			popular: true,
			trending: true,
			progress: 45
	},
	{
			id: 9,
			category: 'الرياضيات',
			image: '/assets/images/course/course-python.jpg',
			title: 'دليل المبتدئين النهائي لتعلم الرياضيات خطوة بخطوة',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'جميلة العراوي',
			instructor_image: '/assets/images/avatar/avatar-6.jpg',
			status: 'مباشر',
			level: 'مبتدئ',
			duration: '2س 46د',
			price: 750,
			discount: 150,
			rating: 4.5,
			ratingby: 11500,
			recommended: true,
			popular: true,
			trending: true,
			progress: 59
	},
	{
			id: 10,
			category: 'الفيزياء',
			image: '/assets/images/course/course-angular.jpg',
			title: 'بدء تطوير الفيزياء مع التجربة وبيانات MongoDB',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'سعيد الجابري',
			instructor_image: '/assets/images/avatar/avatar-5.jpg',
			status: 'مباشر',
			level: 'متوسط',
			duration: '2س 40د',
			price: 750,
			discount: 150,
			rating: 4.5,
			ratingby: 13500,
			recommended: true,
			popular: true,
			trending: true,
			progress: 95
	},
	{
			id: 11,
			category: 'الرياضيات',
			image: '/assets/images/course/course-python.jpg',
			title: 'دورة الرياضيات: بناء التطبيقات الويب',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'أحمد بن سعيد',
			instructor_image: '/assets/images/avatar/avatar-9.jpg',
			status: 'مباشر',
			level: 'مبتدئ',
			duration: '2س 46د',
			price: 750,
			discount: 150,
			rating: 4.5,
			ratingby: 7800,
			recommended: true,
			popular: true,
			trending: true,
			progress: 45
	},
	{
			id: 12,
			category: 'الفلسفة',
			image: '/assets/images/course/course-node.jpg',
			title: 'الفلسفة: دليل المبتدئين الشامل لتعلم الفلسفة خطوة بخطوة',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'جميلة العراوي',
			instructor_image: '/assets/images/avatar/avatar-6.jpg',
			status: 'مباشر',
			level: 'مبتدئ',
			duration: '1س 46د',
			price: 750,
			discount: 150,
			rating: 4.5,
			ratingby: 3600,
			recommended: true,
			popular: true,
			trending: true,
			progress: 95
	},
	{
			id: 13,
			category: 'الرياضيات',
			image: '/assets/images/course/course-python.jpg',
			title: 'الرياضيات في التطبيق: دليل خطوة بخطوة',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'عبد الرحمن',
			instructor_image: '/assets/images/avatar/avatar-10.jpg',
			status: 'مباشر',
			level: 'متقدم',
			duration: '1س 00د',
			price: 220,
			discount: 50,
			rating: 5.0,
			ratingby: 2500,
			recommended: true,
			popular: false,
			trending: true,
			progress: 55
	},
	{
			id: 14,
			category: 'الفيزياء',
			image: '/assets/images/course/course-angular.jpg',
			title: 'فيزياء للأداء العالي: دورة متقدمة',
			date_added: 'أضيف في 4 يوليو، 2021',
			instructor_name: 'سعيد الجابري',
			instructor_image: '/assets/images/avatar/avatar-11.jpg',
			status: 'مباشر',
			level: 'متقدم',
			duration: '3س 00د',
			price: 800,
			discount: 100,
			rating: 4.8,
			ratingby: 7000,
			recommended: true,
			popular: true,
			trending: true,
			progress: 70
	},
	{
			id: 15,
			category: 'الفلسفة',
			image: '/assets/images/course/course-node.jpg',
			title: 'الفلسفة من الألف إلى الياء',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'فاطمة الزهراء',
			instructor_image: '/assets/images/avatar/avatar-12.jpg',
			status: 'مباشر',
			level: 'متقدم',
			duration: '2س 30د',
			price: 900,
			discount: 100,
			rating: 4.7,
			ratingby: 3400,
			recommended: true,
			popular: true,
			trending: true,
			progress: 60
	},
	{
			id: 16,
			category: 'الرياضيات',
			image: '/assets/images/course/course-python.jpg',
			title: 'كيفية استخدام الرياضيات في البرمجة',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'علي الصغير',
			instructor_image: '/assets/images/avatar/avatar-13.jpg',
			status: 'مباشر',
			level: 'متوسط',
			duration: '1س 45د',
			price: 650,
			discount: 75,
			rating: 4.5,
			ratingby: 5500,
			recommended: true,
			popular: true,
			trending: true,
			progress: 85
	},
	{
			id: 17,
			category: 'الفيزياء',
			image: '/assets/images/course/course-angular.jpg',
			title: 'الفيزياء الحديثة: الدورة الشاملة',
			date_added: 'أضيف في 6 يوليو، 2021',
			instructor_name: 'محمد العلوي',
			instructor_image: '/assets/images/avatar/avatar-14.jpg',
			status: 'مباشر',
			level: 'متقدم',
			duration: '4س 00د',
			price: 1000,
			discount: 200,
			rating: 4.9,
			ratingby: 3000,
			recommended: true,
			popular: true,
			trending: true,
			progress: 95
	},
	{
			id: 18,
			category: 'الفلسفة',
			image: '/assets/images/course/course-node.jpg',
			title: 'الفلسفة وتاريخها: دورة أساسية',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'يوسف بنحسن',
			instructor_image: '/assets/images/avatar/avatar-15.jpg',
			status: 'مباشر',
			level: 'متقدم',
			duration: '2س 30د',
			price: 800,
			discount: 100,
			rating: 4.6,
			ratingby: 4100,
			recommended: true,
			popular: true,
			trending: true,
			progress: 90
	},
	{
			id: 19,
			category: 'الرياضيات',
			image: '/assets/images/course/course-python.jpg',
			title: 'الرياضيات المتقدمة: دورة مكثفة',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'سارة بنسعيد',
			instructor_image: '/assets/images/avatar/avatar-16.jpg',
			status: 'مباشر',
			level: 'متقدم',
			duration: '2س 00د',
			price: 700,
			discount: 50,
			rating: 4.8,
			ratingby: 5500,
			recommended: true,
			popular: true,
			trending: true,
			progress: 65
	},
	{
			id: 20,
			category: 'الفلسفة',
			image: '/assets/images/course/course-node.jpg',
			title: 'الفلسفة والعقل: دورة أساسية',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'عبد الرحمن',
			instructor_image: '/assets/images/avatar/avatar-17.jpg',
			status: 'مباشر',
			level: 'مبتدئ',
			duration: '3س 30د',
			price: 800,
			discount: 100,
			rating: 4.7,
			ratingby: 3600,
			recommended: true,
			popular: true,
			trending: true,
			progress: 80
	},
	{
			id: 21,
			category: 'الرياضيات',
			image: '/assets/images/course/course-python.jpg',
			title: 'الرياضيات والعلوم: علاقة متينة',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'علي الصغير',
			instructor_image: '/assets/images/avatar/avatar-18.jpg',
			status: 'مباشر',
			level: 'متوسط',
			duration: '3س 00د',
			price: 750,
			discount: 75,
			rating: 4.5,
			ratingby: 4700,
			recommended: true,
			popular: true,
			trending: true,
			progress: 90
	},
	{
			id: 22,
			category: 'الفيزياء',
			image: '/assets/images/course/course-angular.jpg',
			title: 'مفاهيم أساسية في الفيزياء الكمية',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'محمد العلوي',
			instructor_image: '/assets/images/avatar/avatar-19.jpg',
			status: 'مباشر',
			level: 'متقدم',
			duration: '3س 15د',
			price: 850,
			discount: 150,
			rating: 4.9,
			ratingby: 3700,
			recommended: true,
			popular: true,
			trending: true,
			progress: 85
	},
	{
			id: 23,
			category: 'الفلسفة',
			image: '/assets/images/course/course-node.jpg',
			title: 'أساسيات الفلسفة القديمة',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'جميلة العراوي',
			instructor_image: '/assets/images/avatar/avatar-20.jpg',
			status: 'مباشر',
			level: 'مبتدئ',
			duration: '2س 00د',
			price: 750,
			discount: 100,
			rating: 4.7,
			ratingby: 3200,
			recommended: true,
			popular: true,
			trending: true,
			progress: 80
	},
	{
			id: 24,
			category: 'الرياضيات',
			image: '/assets/images/course/course-python.jpg',
			title: 'التفوق في الرياضيات: دورة مكثفة',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'عبد الرحمن',
			instructor_image: '/assets/images/avatar/avatar-21.jpg',
			status: 'مباشر',
			level: 'متقدم',
			duration: '2س 30د',
			price: 900,
			discount: 200,
			rating: 5.0,
			ratingby: 5000,
			recommended: true,
			popular: true,
			trending: true,
			progress: 90
	},
	{
			id: 25,
			category: 'الفيزياء',
			image: '/assets/images/course/course-angular.jpg',
			title: 'تجارب فيزياء متقدمة',
			date_added: 'أضيف في 5 يوليو، 2021',
			instructor_name: 'سعيد الجابري',
			instructor_image: '/assets/images/avatar/avatar-22.jpg',
			status: 'مباشر',
			level: 'متقدم',
			duration: '2س 15د',
			price: 750,
			discount: 100,
			rating: 4.6,
			ratingby: 4100,
			recommended: true,
			popular: true,
			trending: true,
			progress: 70
	}
];
